# Generated by Django 5.1.4 on 2025-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала допуска')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания допуска')),
            ],
            options={
                'verbose_name': 'Эксперт-допуск',
                'verbose_name_plural': 'Эксперт-допуск',
            },
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название допуска')),
            ],
            options={
                'verbose_name': 'Допуск',
                'verbose_name_plural': 'Допуска',
            },
        ),
        migrations.CreateModel(
            name='ExpertLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начало работы в лаборатории')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец работы в лаюоратории')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лаборатории')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
    ]
