# Generated by Django 5.1.4 on 2025-01-06 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertexpertisearea',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_expertisearea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='experts',
            field=models.ManyToManyField(related_name='expertiseareas', through='expert.ExpertExpertiseArea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertexpertisearea',
            name='expertisearea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_expertisearea', to='expert.expertisearea'),
        ),
        migrations.AddField(
            model_name='expertlaboratory',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_laboratory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='experts',
            field=models.ManyToManyField(related_name='laboratories', through='expert.ExpertLaboratory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertlaboratory',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_laboratory', to='expert.laboratory'),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertiseareas', to='expert.laboratory'),
        ),
    ]
