# Generated by Django 5.1.4 on 2025-01-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
            },
        ),
        migrations.CreateModel(
            name='RankAndType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_type', to='main.rank')),
            ],
        ),
        migrations.CreateModel(
            name='RankType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('ranks', models.ManyToManyField(related_name='types', through='main.RankAndType', to='main.rank')),
            ],
            options={
                'verbose_name': 'Тип звания',
                'verbose_name_plural': 'Типы званий',
            },
        ),
        migrations.AddField(
            model_name='rankandtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_rank', to='main.ranktype'),
        ),
        migrations.AddConstraint(
            model_name='rankandtype',
            constraint=models.UniqueConstraint(fields=('rank', 'type'), name='rank_type_constraint'),
        ),
    ]
